version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - rm -rf ~/.aws/cli/cache
  build:
    commands:
      - aws eks --region ap-northeast-2 update-kubeconfig --name videostream
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 971422710496.dkr.ecr.ap-northeast-2.amazonaws.com/videoweb
      - docker build -t videostream .
      - docker tag videostream:latest 971422710496.dkr.ecr.ap-northeast-2.amazonaws.com/videoweb:latest
      - docker push 971422710496.dkr.ecr.ap-northeast-2.amazonaws.com/videoweb:latest
      - aws eks update-kubeconfig --region ap-northeast-2 --name videostream
      - kubectl apply -f deployment.yml > kubectl_apply_deployment.log 2>&1 || true
      - kubectl apply -f service.yml > kubectl_apply_service.log  2>&1 || true
      - kubectl apply -f ingress.yml > kubectl_apply_ingress.log  2>&1 || true
      
      
