version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  build:
    commands:
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 971422710496.dkr.ecr.ap-northeast-2.amazonaws.com/videoweb
      - docker build -t videostream .
      - docker tag videostream:latest 971422710496.dkr.ecr.ap-northeast-2.amazonaws.com/videoweb:latest
      - docker push 971422710496.dkr.ecr.ap-northeast-2.amazonaws.com/videoweb:latest
      - aws eks update-kubeconfig --region ap-northeast-2 --name videostream
      
      - kubectl config view > kubectl_config.log
      - kubectl get nodes > kubectl_get_nodes.log
      - kubectl apply -f deployment.yml > kubectl_apply_deployment.log
      - kubectl apply -f service.yml > kubectl_apply_service.log
      - kubectl apply -f ingress.yml > kubectl_apply_ingress.log
      - aws s3 cp kubectl_config.log s3://jongho3165/kubectl_config.log
      - aws s3 cp kubectl_get_nodes.log s3://jongho3165/kubectl_get_nodes.log
      - aws s3 cp kubectl_apply_deployment.log s3://jongho3165/kubectl_apply_deployment.log
      - aws s3 cp kubectl_apply_service.log s3://jongho3165/kubectl_apply_service.log
      - aws s3 cp kubectl_apply_ingress.log 
      
      
      
