version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - rm -rf ~/.aws/cli/cache
  build:
    commands:
      - aws eks --region ap-northeast-2 update-kubeconfig --name videostream
      - aws sts get-caller-identity > aws.log 2>&1 || true
      - aws s3 cp aws.log s3://jongho3165/aws.log || true
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 971422710496.dkr.ecr.ap-northeast-2.amazonaws.com/videoweb
      - docker build -t videostream .
      - docker tag videostream:latest 971422710496.dkr.ecr.ap-northeast-2.amazonaws.com/videoweb:latest
      - docker push 971422710496.dkr.ecr.ap-northeast-2.amazonaws.com/videoweb:latest
      - aws eks update-kubeconfig --region ap-northeast-2 --name videostream
      - export KUBECONFIG=/root/.kube/config
      - ls -al > ls.log
      - kubectl get rolebinding,clusterrolebinding --all-namespaces | grep $(kubectl config view --minify --output 'jsonpath={..user}')  > brother.log 2>&1 || true
      - kubectl config view > kubectl_config.log 2>&1
      - kubectl get all -A -v=8 > kubectl_get_nodes.log 2>&1 || true
      - kubectl apply -f deployment.yml > kubectl_apply_deployment.log 2>&1 || true
      - kubectl apply -f service.yml > kubectl_apply_service.log  2>&1 || true
      - kubectl apply -f ingress.yml > kubectl_apply_ingress.log  2>&1 || true
      - aws s3 cp kubectl_config.log s3://jongho3165/kubectl_config.log  || true
      - aws s3 cp kubectl_get_nodes.log s3://jongho3165/kubectl_get_nodes.log || true
      - aws s3 cp kubectl_apply_deployment.log s3://jongho3165/kubectl_apply_deployment.log || true
      - aws s3 cp kubectl_apply_service.log s3://jongho3165/kubectl_apply_service.log || true
      - aws s3 cp kubectl_apply_ingress.log s3://jongho3165/kubectl_apply_service.log || true
      - aws s3 cp ls.log s3://jongho3165/ls.log || true
      - aws s3 cp brother.log s3://jongho3165/brother.log || true
      
      
